export const iBungeeInboxAbi = [
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_permit2', type: 'address' },
      { internalType: 'address', name: '_bungeeGateway', type: 'address' },
      { internalType: 'address payable', name: '_wrappedNativeToken', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'InvalidChainId', type: 'error' },
  { inputs: [], name: 'InvalidMsgValue', type: 'error' },
  { inputs: [], name: 'InvalidNonce', type: 'error' },
  { inputs: [], name: 'InvalidReceiver', type: 'error' },
  { inputs: [], name: 'InvalidSender', type: 'error' },
  { inputs: [], name: 'InvalidTokenAddress', type: 'error' },
  { inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }], name: 'NoPermit', type: 'error' },
  { inputs: [], name: 'OnlyNominee', type: 'error' },
  { inputs: [], name: 'OnlyOwner', type: 'error' },
  { inputs: [], name: 'RequestAlreadyFulfilled', type: 'error' },
  { inputs: [], name: 'RequestAlreadyWithdraw', type: 'error' },
  { inputs: [], name: 'RequestDoesNotExist', type: 'error' },
  { inputs: [], name: 'RequestNotWithdrawn', type: 'error' },
  { inputs: [], name: 'TransferFailed', type: 'error' },
  { inputs: [], name: 'TransferFailed', type: 'error' },
  { inputs: [], name: 'WrongAffiliateFeeLength', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'claimer', type: 'address' }],
    name: 'OwnerClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'nominee', type: 'address' }],
    name: 'OwnerNominated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'grantee', type: 'address' },
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'revokee', type: 'address' },
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'requestHash', type: 'bytes32' },
      { indexed: false, internalType: 'address', name: 'refundAddress', type: 'address' },
      { indexed: false, internalType: 'bytes', name: 'request', type: 'bytes' },
    ],
    name: 'SingleOutputRequestCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'bytes32', name: 'requestHash', type: 'bytes32' }],
    name: 'SingleOutputRequestWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'requestHash', type: 'bytes32' },
      { indexed: false, internalType: 'address', name: 'refundAddress', type: 'address' },
      { indexed: false, internalType: 'bytes', name: 'request', type: 'bytes' },
    ],
    name: 'SwapRequestCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'bytes32', name: 'requestHash', type: 'bytes32' }],
    name: 'SwapRequestWithdrawn',
    type: 'event',
  },
  {
    inputs: [],
    name: 'BUNGEE_GATEWAY',
    outputs: [{ internalType: 'contract IBungeeGateway', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NATIVE_TOKEN_ADDRESS',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'PERMIT2',
    outputs: [{ internalType: 'contract IPermit2', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WRAPPED_NATIVE_TOKEN',
    outputs: [{ internalType: 'contract WETH', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'claimOwner', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      {
        components: [
          {
            components: [
              { internalType: 'uint256', name: 'originChainId', type: 'uint256' },
              { internalType: 'uint256', name: 'destinationChainId', type: 'uint256' },
              { internalType: 'uint256', name: 'deadline', type: 'uint256' },
              { internalType: 'uint256', name: 'nonce', type: 'uint256' },
              { internalType: 'address', name: 'sender', type: 'address' },
              { internalType: 'address', name: 'receiver', type: 'address' },
              { internalType: 'address', name: 'delegate', type: 'address' },
              { internalType: 'address', name: 'bungeeGateway', type: 'address' },
              { internalType: 'uint32', name: 'switchboardId', type: 'uint32' },
              { internalType: 'address', name: 'inputToken', type: 'address' },
              { internalType: 'uint256', name: 'inputAmount', type: 'uint256' },
              { internalType: 'address', name: 'outputToken', type: 'address' },
              { internalType: 'uint256', name: 'minOutputAmount', type: 'uint256' },
              { internalType: 'uint256', name: 'refuelAmount', type: 'uint256' },
            ],
            internalType: 'struct BasicRequest',
            name: 'basicReq',
            type: 'tuple',
          },
          { internalType: 'address', name: 'swapOutputToken', type: 'address' },
          { internalType: 'uint256', name: 'minSwapOutput', type: 'uint256' },
          { internalType: 'bytes32', name: 'metadata', type: 'bytes32' },
          { internalType: 'bytes', name: 'affiliateFees', type: 'bytes' },
          { internalType: 'uint256', name: 'minDestGas', type: 'uint256' },
          { internalType: 'bytes', name: 'destinationPayload', type: 'bytes' },
          { internalType: 'address', name: 'exclusiveTransmitter', type: 'address' },
        ],
        internalType: 'struct Request',
        name: 'singleOutputRequest',
        type: 'tuple',
      },
      { internalType: 'address', name: 'refundAddress', type: 'address' },
    ],
    name: 'createRequest',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role_', type: 'bytes32' },
      { internalType: 'address', name: 'grantee_', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role_', type: 'bytes32' },
      { internalType: 'address', name: 'address_', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '_hash', type: 'bytes32' },
      { internalType: 'bytes', name: '_signature', type: 'bytes' },
    ],
    name: 'isValidSignature',
    outputs: [{ internalType: 'bytes4', name: 'magicValue', type: 'bytes4' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'nominee_', type: 'address' }],
    name: 'nominateOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nominee',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'nonce', type: 'uint256' }],
    name: 'requestInbox',
    outputs: [
      { internalType: 'address', name: 'refundAddress', type: 'address' },
      { internalType: 'bytes32', name: 'typedDataHash', type: 'bytes32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'rescue',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role_', type: 'bytes32' },
      { internalType: 'address', name: 'revokee_', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              { internalType: 'uint256', name: 'originChainId', type: 'uint256' },
              { internalType: 'uint256', name: 'destinationChainId', type: 'uint256' },
              { internalType: 'uint256', name: 'deadline', type: 'uint256' },
              { internalType: 'uint256', name: 'nonce', type: 'uint256' },
              { internalType: 'address', name: 'sender', type: 'address' },
              { internalType: 'address', name: 'receiver', type: 'address' },
              { internalType: 'address', name: 'delegate', type: 'address' },
              { internalType: 'address', name: 'bungeeGateway', type: 'address' },
              { internalType: 'uint32', name: 'switchboardId', type: 'uint32' },
              { internalType: 'address', name: 'inputToken', type: 'address' },
              { internalType: 'uint256', name: 'inputAmount', type: 'uint256' },
              { internalType: 'address', name: 'outputToken', type: 'address' },
              { internalType: 'uint256', name: 'minOutputAmount', type: 'uint256' },
              { internalType: 'uint256', name: 'refuelAmount', type: 'uint256' },
            ],
            internalType: 'struct BasicRequest',
            name: 'basicReq',
            type: 'tuple',
          },
          { internalType: 'address', name: 'swapOutputToken', type: 'address' },
          { internalType: 'uint256', name: 'minSwapOutput', type: 'uint256' },
          { internalType: 'bytes32', name: 'metadata', type: 'bytes32' },
          { internalType: 'bytes', name: 'affiliateFees', type: 'bytes' },
          { internalType: 'uint256', name: 'minDestGas', type: 'uint256' },
          { internalType: 'bytes', name: 'destinationPayload', type: 'bytes' },
          { internalType: 'address', name: 'exclusiveTransmitter', type: 'address' },
        ],
        internalType: 'struct Request',
        name: 'singleOutputRequest',
        type: 'tuple',
      },
    ],
    name: 'withdrawFunds',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'typedDataHash', type: 'bytes32' }],
    name: 'withdrawnInbox',
    outputs: [{ internalType: 'bool', name: 'withdrawn', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
] as const;
